# .github/workflows/ci.yml
name: Python CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout DieKinchick
        uses: actions/checkout@v3

      - name: Установка Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Проверка кода flake8
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Запуск тестов
        run: |
          run: python -m unittest discover -s tests
#          unittest discover -s tests

      - name: Проверка форматирования (black)
        run: |
          pip install black
          black --check .

